__author__ = 'omrim'

class Services(object):


# isSupportMobile is just True
# None is for non existing values
    #  need to find out from their website
#setupFee is missing
#contract length
#countries deployed in

    leap = { 'serviceID': 1,
             'serviceName': 'leap',
             'monthlyFee': 15,
             'onePercent': 0.95,
             'oneFix': 0.1,
             'twoPercent': 0.95,
             'twoFix': 0.1,
             'threePercent': 0.95,
             'threeFix': 0.1,
             'fourPercent': 0.95,
             'fourFix': 0.1,
             'fivePercent': 0.95,
             'fiveFix': 0.1,
             'chargebackFee': 15,
             'internationalRate': 0.95,
             'isSupportMobile': True,
             'currency': 'usd',
             'vmQPercent': 0.95,
             'vmQFix': 0.1,
             'vmNQPercent': 0.95,
             'vmNQFix': 0.1,
             'axpPercent': 2.89,
             'axpFix': 0.1,
             'diners': None
            }

    intuit = { 'serviceID': 2,
             'serviceName': 'intuit',
             'monthlyFee': 0.0,
             'onePercent': 1.75,
             'oneFix': 0.5,
             'twoPercent': 1.75,
             'twoFix': 0.5,
             'threePercent': 1.75,
             'threeFix': 0.5,
             'fourPercent': None,
             'fourFix': None,
             'fivePercent': None,
             'fiveFix': None,
             'chargebackFee': 20,
             'internationalRate': None,
             'isSupportMobile': True,
             'currency': 'usd',
             'vmQPercent': 1.75,
             'vmQFix': 0.5,
             'vmNQPercent': 1.75,
             'vmNQFix': 0.5,
             'axpPercent': 2.89,
             'axpFix': 0.0,
             'diners': None
            }

    payza = { 'serviceID': 3,
             'serviceName': 'payza',
             'monthlyFee': None,
             'onePercent': None,
             'oneFix': None,
             'twoPercent': None,
             'twoFix': None,
             'threePercent': None,
             'threeFix': None,
             'fourPercent': None,
             'fourFix': None,
             'fivePercent': None,
             'fiveFix': None,
             'chargebackFee': 35,
             'internationalRate': 2.5,
             'isSupportMobile': True,
             'currency': 'usd',
             'vmQPercent': 2.5,
             'vmQFix': 0.25,
             'vmNQPercent': None,
             'vmNQFix': None,
             'axpPercent': None,
             'axpFix': None,
             'diners': None
            }

    payPal = { 'serviceID': 4,
             'serviceName': 'paypal',
             'monthlyFee': 0,
             'onePercent': 2.9,
             'oneFix': 0.3,
             'twoPercent': 2.9,
             'twoFix': 0.3,
             'threePercent': 2.5,
             'threeFix': 0.3,
             'fourPercent': 2.2,
             'fourFix': 0.3,
             'fivePercent': 1.9,
             'fiveFix': 0.3,
             'chargebackFee': 20,
             'internationalRate': 0.0,
             'isSupportMobile': True,
             'currency': 'usd',
             'vmQPercent': 2.9,
             'vmQFix': 0.3,
             'vmNQPercent': 2.9,
             'vmNQFix': 0.3,
             'axpPercent': 2.9,
             'axpFix': 0.3,
             'diners': None
            }


    skrill = { 'serviceID': 5,
             'serviceName': 'skrill',
             'monthlyFee': None,
             'onePercent': 2.9,
             'oneFix': 0.29,
             'twoPercent': 2.9,
             'twoFix': 0.29,
             'threePercent': 2.4,
             'threeFix': 0.29,
             'fourPercent': 2.00,
             'fourFix': 0.29,
             'fivePercent': 1.7,
             'fiveFix': 0.29,
             'chargebackFee': 20,
             'internationalRate': 0.0,
             'isSupportMobile': True,
             'currency': 'usd',
             'vmQPercent': 2.9,
             'vmQFix': 0.29,
             'vmNQPercent': 2.9,
             'vmNQFix': 0.29,
             'axpPercent': 2.9,
             'axpFix': 0.29,
             'diners': None
            }


    square = { 'serviceID': 6,
             'serviceName': 'square',
             'monthlyFee': 275,
             'onePercent': 2.75,
             'oneFix': None,
             'twoPercent': 2.75,
             'twoFix': None,
             'threePercent': None,
             'threeFix': None,
             'fourPercent': None,
             'fourFix': None,
             'fivePercent': None,
             'fiveFix': None,
             'chargebackFee': 0.0,
             'internationalRate': None,
             'isSupportMobile': True,
             'currency': 'usd',
             'vmQPercent': 2.75,
             'vmQFix': 0.0,
             'vmNQPercent': 2.75,
             'vmNQFix': 0.0,
             'axpPercent': None,
             'axpFix': None,
             'diners': None
            }


    brainTree = { 'serviceID': 7,
             'serviceName': 'brainTree',
             'monthlyFee': 0.0,
             'onePercent': 2.9,
             'oneFix': 0.3,
             'twoPercent': 2.9,
             'twoFix': 0.3,
             'threePercent': 2.9,
             'threeFix': 0.3,
             'fourPercent': 2.9,
             'fourFix': 0.3,
             'fivePercent': 2.9,
             'fiveFix': 0.3,
             'chargebackFee': 15,
             'internationalRate':0.0,
             'isSupportMobile': True,
             'currency': 'usd',
             'vmQPercent': 2.9,
             'vmQFix': 0.3,
             'vmNQPercent': 2.9,
             'vmNQFix': 0.3,
             'axpPercent': 0.0,
             'axpFix': 0.0,
             'diners': None
            }


    amazonPayments = { 'serviceID': 8,
             'serviceName': 'amazonPayments',
             'monthlyFee': 0.0,
             'onePercent': 5.0,
             'oneFix': 0.0,
             'twoPercent': 2.9,
             'twoFix': 0.3,
             'threePercent': 2.5,
             'threeFix': 0.3,
             'fourPercent': 2.2,
             'fourFix': 0.3,
             'fivePercent': 1.9,
             'fiveFix': 0.3,
             'chargebackFee': 10,
             'internationalRate': 2.5,
             'isSupportMobile': True,
             'currency': 'usd',
             'vmQPercent': 2.9,
             'vmQFix': 0.30,
             'vmNQPercent': 2.9,
             'vmNQFix': 0.30,
             'axpPercent': 2.9,
             'axpFix': 0.30,
             'diners': None
            }



    googleWallet = { 'serviceID': 9,
             'serviceName': 'googleWallet',
             'monthlyFee': 0,
             'onePercent': 2.9,
             'oneFix': 0.3,
             'twoPercent': 2.9,
             'twoFix': 0.3,
             'threePercent': 2.9,
             'threeFix': 0.3,
             'fourPercent': 2.9,
             'fourFix': 0.3,
             'fivePercent': 2.9,
             'fiveFix': 0.3,
             'chargebackFee': 10,
             'internationalRate': 0.0,
             'isSupportMobile': True,
             'currency': 'usd',
             'vmQPercent': 2.9,
             'vmQFix': 0.3,
             'vmNQPercent': 2.9,
             'vmNQFix': 0.3,
             'axpPercent': 2.9,
             'axpFix': 0.3,
             'diners': None
            }


    twoCheckOut = { 'serviceID': 10,
             'serviceName': 'twoCheckOut',
             'monthlyFee': 0,
             'onePercent': 5.5,
             'oneFix': 0.45,
             'twoPercent': 5.5,
             'twoFix': 0.45,
             'threePercent': 5.5,
             'threeFix': 0.45,
             'fourPercent': None,
             'fourFix': None,
             'fivePercent': None,
             'fiveFix': None,
             'chargebackFee': 16,
             'internationalRate': 2.5,
             'isSupportMobile': True,
             'currency': 'usd',
             'vmQPercent': 5.5,
             'vmQFix': 0.45,
             'vmNQPercent': 5.5,
             'vmNQFix': 0.45,
             'axpPercent': None,
             'axpFix': None,
             'diners': None
            }


    stripe = { 'serviceID': 11,
             'serviceName': 'stripe',
             'monthlyFee': 0,
             'onePercent': 2.9,
             'oneFix': 0.3,
             'twoPercent': 2.9,
             'twoFix': 0.3,
             'threePercent': 2.9,
             'threeFix': 0.3,
             'fourPercent': 2.9,
             'fourFix': 0.3,
             'fivePercent': 2.9,
             'fiveFix': 0.3,
             'chargebackFee': 35,
             'internationalRate': 2.5,
             'isSupportMobile': True,
             'currency': 'usd',
             'vmQPercent': None,
             'vmQFix': None,
             'vmNQPercent': None,
             'vmNQFix': None,
             'axpPercent': None,
             'axpFix': None,
             'diners': None
            }


    wePay = { 'serviceID': 12,
             'serviceName': 'wePay',
             'monthlyFee': 0,
             'onePercent': 2.9,
             'oneFix': 0.3,
             'twoPercent': 2.9,
             'twoFix': 0.3,
             'threePercent': 2.9,
             'threeFix': 0.3,
             'fourPercent': 2.9,
             'fourFix': 0.3,
             'fivePercent': 2.9,
             'fiveFix': 0.3,
             'chargebackFee': 35,
             'internationalRate': None,
             'isSupportMobile': True,
             'currency': 'usd',
             'vmQPercent': 2.9,
             'vmQFix': 0.30,
             'vmNQPercent': 2.9,
             'vmNQFix': 0.30,
             'axpPercent': 2.9,
             'axpFix': 0.3,
             'diners': None
            }

    servicesList = [leap, intuit, payza, payPal, skrill, square, brainTree,
                    amazonPayments, googleWallet, twoCheckOut, stripe, wePay]
